/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO 2009 tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package uk.me.g4dpz.appsengine.satellitecloud.jdo.dao;

import java.sql.Date;
import java.sql.Timestamp;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import uk.me.g4dpz.appsengine.satellitecloud.jdo.dto.SatelliteElement;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface SatelliteElementDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public SatelliteElement findByPrimaryKey( long id );

    /**
     * Finds a record.
     */
    public SatelliteElement findByCatalogueNumber( Long catalogueNumber );

    /**
     * Counts records using index inx_satel_catno.
     */
    public int countByCatalogueNumber( Long catalogueNumber );

    /**
     * Finds records using index inx_satel_catno.
     */
    public SatelliteElement findByCatalogueNumber( int offset, int count, Long catalogueNumber );

    /**
     * Deletes records.
     * @return the number of records deleted
     */
    public int deleteSatellite( Long catalogueNumber ) throws DaoException;

    /**
     * Inserts a new record.
     * @return the generated primary key - id
     */
    public long insert( SatelliteElement dto ) throws DaoException;

}
