/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO 2009 tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package uk.me.g4dpz.appsengine.satellitecloud.jdo.dao;

import java.sql.Date;
import java.sql.Timestamp;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import uk.me.g4dpz.appsengine.satellitecloud.jdo.dto.SourceFile;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface SourceFileDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public SourceFile findByPrimaryKey( long id );

    /**
     * Finds a record.
     */
    public SourceFile findByName( String name );

    /**
     * Counts records using index inx_sourcefile_name.
     */
    public int countByName( String name );

    /**
     * Finds records using index inx_sourcefile_name.
     */
    public SourceFile findByName( int offset, int count, String name );

    /**
     * Deletes records.
     * @return the number of records deleted
     */
    public int deleteSourceFile( String name ) throws DaoException;

    /**
     * Inserts a new record.
     * @return the generated primary key - id
     */
    public long insert( SourceFile dto ) throws DaoException;

}
