/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO 2009 tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package uk.me.g4dpz.appsengine.satellitecloud.jdo.dao.gae;


import java.sql.Date;
import java.sql.Timestamp;

import java.util.ArrayList;
import java.util.List;

import javax.jdo.JDOException;
import javax.jdo.JDOObjectNotFoundException;
import javax.jdo.PersistenceManager;
import javax.jdo.Query;

import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;

import com.spoledge.audao.db.dao.gae.GaeAbstractDaoImpl;
import com.spoledge.audao.db.dao.DBException;
import com.spoledge.audao.db.dao.DaoException;

import uk.me.g4dpz.appsengine.satellitecloud.jdo.dao.SatelliteGroupDao;
import uk.me.g4dpz.appsengine.satellitecloud.jdo.dto.SatelliteGroup;
import uk.me.g4dpz.appsengine.satellitecloud.jdo.dto.gae.SatelliteGroupImpl;


/**
 * This is the DAO imlementation class.
 *
 * @author generated
 */
public class SatelliteGroupDaoImpl extends GaeAbstractDaoImpl<SatelliteGroup> implements SatelliteGroupDao {

    public SatelliteGroupDaoImpl( PersistenceManager pm ) {
        super( pm );
    }

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public SatelliteGroup findByPrimaryKey( long id ) {
        SatelliteGroupImpl impl = null;

        try {
            impl = pm.getObjectById( SatelliteGroupImpl.class, id);
        }
        catch (JDOObjectNotFoundException _e) {}

        return impl != null ? impl._getDto() : null;
    }

    /**
     * Finds a record.
     */
    public SatelliteGroup findByName( String name ) {
        return findOne( "name == :_name", name);
    }

    /**
     * Counts records using index inx_satgrp_name.
     */
    public int countByName( String name ) {
        return count( "name == :_name", name);
    }

    /**
     * Finds records using index inx_satgrp_name.
     */
    public SatelliteGroup findByName( int offset, int count, String name ) {
        return findOne( "name == :_name", name);
    }

    /**
     * Deletes records.
     * @return the number of records deleted
     */
    public int deleteSatelliteGroup( String name ) throws DaoException {
        return deleteMany( "[CDATA[name=?]]", name);
    }

    /**
     * Inserts a new record.
     * @return the generated primary key - id
     */
    public long insert( SatelliteGroup dto ) throws DaoException {

        debugSql( "insert", dto );

        try {
            SatelliteGroupImpl impl = new SatelliteGroupImpl();

            if ( dto.getName() != null ) {
                checkMaxLength( "name", dto.getName(), 255 );
            }
            impl.setName( dto.getName());

            if ( dto.getSourceId() == null ) {
                // none for GAE
            }
            else {
                impl.setSourceId( dto.getSourceId());
            }

            pm.makePersistent( impl );

            dto.setId( impl.getId().getId());

            return dto.getId();
        }
        catch (JDOException e) {
            errorSql( e, "insert", dto );

            throw new DaoException( e );
        }
    }

    /**
     * Returns the table name.
     */
    public String getTableName() {
        return null;
    }

    protected Query getQuery() {
        return pm.newQuery( SatelliteGroupImpl.class );
    }

    protected SatelliteGroup fetch( Query q, Object... params ) {
        SatelliteGroupImpl impl = (SatelliteGroupImpl) execute( q, params );

        return impl != null ? impl._getDto() : null;
    }

    protected SatelliteGroup[] fetchArray( Query q, Object... params ) {
        List<?> list = (List<?>) execute( q, params );

        SatelliteGroup[] ret = new SatelliteGroup[ list.size() ];

        int index=0;
        for ( Object o : list ) {
            SatelliteGroupImpl impl = (SatelliteGroupImpl) o;
            ret[ index++ ] = impl._getDto();
        }

        return ret;
    }

}
