/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO 2009 tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package uk.me.g4dpz.appsengine.satellitecloud.jdo.dto.gae;

import javax.jdo.annotations.Extension;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.PrimaryKey;

import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;

import com.spoledge.audao.db.dto.gae.GaeAbstractDtoImpl;

import uk.me.g4dpz.appsengine.satellitecloud.jdo.dto.SatelliteElement;

/**
 * This is a DTO class.
 *
 * @author generated
 */
@PersistenceCapable(identityType = IdentityType.APPLICATION)
public class SatelliteElementImpl extends GaeAbstractDtoImpl {

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    @PrimaryKey
    @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
    private Key id;

    @Persistent
    private Long catalogueNumber;

    @Persistent
    private Long elementSet;

    @Persistent
    private Long groupId;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public SatelliteElementImpl() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public Key getId() {
        return id;
    }

    public void setId( Key _val) {
        this.id = _val;
    }

    public Long getCatalogueNumber() {
        return catalogueNumber;
    }

    public void setCatalogueNumber( Long _val) {
        this.catalogueNumber = _val;
    }

    public Long getElementSet() {
        return elementSet;
    }

    public void setElementSet( Long _val) {
        this.elementSet = _val;
    }

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId( Long _val) {
        this.groupId = _val;
    }

    /**
     * Returns the DTO mirror.
     */
    public SatelliteElement _getDto() {
        SatelliteElement _dto = new SatelliteElement();
        _copyTo( _dto );

        return _dto;
    }

    /**
     * Copies this DTOImpl into the DTO mirror.
     */
    public void _copyTo( SatelliteElement _dto ) {
        _dto.setId( getId().getId());
        _dto.setCatalogueNumber( getCatalogueNumber());
        _dto.setElementSet( getElementSet());
        _dto.setGroupId( getGroupId());
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "id", id );
        append( sb, "catalogueNumber", catalogueNumber );
        append( sb, "elementSet", elementSet );
        append( sb, "groupId", groupId );
    }
}
