/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO 2009 tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package uk.me.g4dpz.appsengine.satellitecloud.jdo.dto.gae;

import javax.jdo.annotations.Extension;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.PrimaryKey;

import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;

import com.spoledge.audao.db.dto.gae.GaeAbstractDtoImpl;

import uk.me.g4dpz.appsengine.satellitecloud.jdo.dto.SourceFile;

/**
 * This is a DTO class.
 *
 * @author generated
 */
@PersistenceCapable(identityType = IdentityType.APPLICATION)
public class SourceFileImpl extends GaeAbstractDtoImpl {

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    @PrimaryKey
    @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
    private Key id;

    @Persistent
    private String name;

    @Persistent
    private String url;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public SourceFileImpl() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public Key getId() {
        return id;
    }

    public void setId( Key _val) {
        this.id = _val;
    }

    public String getName() {
        return name;
    }

    public void setName( String _val) {
        this.name = _val;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl( String _val) {
        this.url = _val;
    }

    /**
     * Returns the DTO mirror.
     */
    public SourceFile _getDto() {
        SourceFile _dto = new SourceFile();
        _copyTo( _dto );

        return _dto;
    }

    /**
     * Copies this DTOImpl into the DTO mirror.
     */
    public void _copyTo( SourceFile _dto ) {
        _dto.setId( getId().getId());
        _dto.setName( getName());
        _dto.setUrl( getUrl());
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "id", id );
        append( sb, "name", name );
        append( sb, "url", url );
    }
}
