/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO 2009 tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package uk.me.g4dpz.appsengine.satellitecloud.jdo.dao.gae;


import javax.jdo.PersistenceManager;
import javax.jdo.PersistenceManagerFactory;

import com.spoledge.audao.db.dao.gae.PersistenceManagerProvider;

import uk.me.g4dpz.appsengine.satellitecloud.jdo.dao.*;


/**
 * This is the main implementation class for obtaining DAO objects.
 * @author generated
 */
public class DaoFactoryImpl extends DaoFactory.Factory {
    private static PersistenceManagerProvider persistenceManagerProvider;

    public static PersistenceManager getPersistenceManager() {
        return persistenceManagerProvider.getPersistenceManager();
    }

    public static void setPersistenceManagerProvider( PersistenceManagerProvider persistenceManagerProvider ) {
        DaoFactoryImpl.persistenceManagerProvider = persistenceManagerProvider;
    }

    public SatelliteElementDao createSatelliteElementDao() {
        return new SatelliteElementDaoImpl( getPersistenceManager() );
    }

    public SatelliteGroupDao createSatelliteGroupDao() {
        return new SatelliteGroupDaoImpl( getPersistenceManager() );
    }

}
